





cd /etc/pki/tls/certs
make testcert
#输入短语 3次

cd ../private/
openssl rsa -in localhost.key -out localhost_nopass.key
#输入短语


useradd -M -s /sbin/nologin saltapi

passwd saltapi





[root@good master.d]# cat api.conf 
rest_cherrypy:
  port: 8888
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/private/localhost_nopass.key
[root@good master.d]# cat eauth.conf 
external_auth:
  pam:
    saltapi:
      - .*
      - '@runner'
      - '@wheel'      